---
title: "Development of ScMaSig Pro"
author: "Priyansh Srivastava"
date: "`r Sys.Date()`"
output: html_document
---

## Required library
```{r}
library(scMaSigPro)
```

## Load Data
```{r}
# Load Simulated Data as SCE
sim.sce <- readRDS("../scMaSigPro_Supp/benchMarking_Normalization/data/output/SimObjectsSCE/skew_density_0.5.RDS")
```

## Convert to scmp object
```{r}
scmp.obj <- as_scmp(sim.sce, from = "sce")
```

## Apply Compression
```{r}
scmp.obj <- squeeze(
  scmp.ob = scmp.obj,
  time.col = "Step",
  path.col = "Group",
  method = "Sturges",
  drop.fac = 0.5,
  verbose = F,
  cluster.count.by = "sum"
)
```

## Make Design 
```{r}
scmp.obj <- sc.make.design.matrix(scmp.obj,
  degree = 2,
  time.col = "binnedTime",
  path.col = "path"
)
```

## Run-Pvector
```{r}
scmp.obj <- sc.p.vector(scmpObj = scmp.obj)
```

# Running T-fit
```{r}
scmp.obj <- sc.T.fit(scmp.obj)
```

# Show Models
```{r, eval=FALSE, message=F, echo=FALSE, warning=FALSE}
showSol(scmp.obj)
```

---

### Evaluation with R-prof
```{r, eval=FALSE}
require(microbenchmark)
time_result <- microbenchmark(
  "scMaSigPro_Pvector" = {
    scmp.obj <- sc_tFit(scmp.obj, p.vector.sig = 0.4)
  },
  "maSigPro_Pvector" = {
    x <- capture.output(p.ob <- p.vector(
      data = as.matrix(gCounts), Q = 0.4,
      design = new.design.file,
      counts = T, family = negative.binomial(10)
    ))
  },
  times = 10
)

# Calculate the elapsed time
sum(time_result$time) / 1e9
autoplot(time_result)
```

---

## Extraction from Monocle3 and Slingshot
```{r, eval=FALSE}
# Load Sample datasets
sce <- readRDS("../../re_analysis_scRNA/setty_et_al/data/output/monocle3/Monocle3UMAPOB/rep1_m3_UMAP_OB_Sling.RDS")
cds <- readRDS("../../re_analysis_scRNA/setty_et_al/data/output/monocle3/Monocle3UMAPOB/rep1_m3_UMAP_OB.RDS")

# Use functions
monocle3Data <- extract_monocle3_components(cds = cds)
slingData <- extract_slingshot_components(sce)
```

---
