---
title: "Development of ScMaSig Pro"
author: "Priyansh Srivastava"
date: "`r Sys.Date()`"
output: html_document
---

## Required library
```{r, message=FALSE}
load <- function() {
  suppressPackageStartupMessages(library(maSigPro))
  suppressPackageStartupMessages(library(MASS))
  suppressPackageStartupMessages(library(tidyverse))
  suppressPackageStartupMessages(library(DHARMa))
  suppressPackageStartupMessages(library(glmmTMB))
  suppressPackageStartupMessages(library(scran))
  suppressPackageStartupMessages(library(scMaSigPro))
}


load_2 <- function() {
  suppressPackageStartupMessages(library(maSigPro))
  suppressPackageStartupMessages(library(MASS))
  suppressPackageStartupMessages(library(tidyverse))
  suppressPackageStartupMessages(library(DHARMa))
  suppressPackageStartupMessages(library(glmmTMB))
  suppressPackageStartupMessages(library(scran))
  suppressPackageStartupMessages(library(assertthat))
  suppressPackageStartupMessages(library(entropy))
  suppressPackageStartupMessages(source("estBinSize.R"))
  suppressPackageStartupMessages(source("utils.R"))
}
```

## Load Data
```{r}
load_2()
sce.test <- readRDS("../data/sce.test.RDS")
cell.metadata <- as.data.frame(colData(sce.test))

x <- entropy_discretize(cell.metadata, time_col = "Step", path_col = "Group")
y <- make.pseudobulk.design(design.file = x, pathCol = "Group", binnedCol = "binnedTime")
z <- make.pseudobulk.counts(
  counts = sce.test@assays@data@listData$counts,
  pseudo_bulk_profile = y, cluster.count.by = "sum"
)

scmp.obj <- sc_makeDesign(sce.object = sce.test)
scmp.obj <- sc_pVector(scmp.obj, p.vector.sig = 0.4)
```

# Running T-fit
```{r, eval=FALSE, message=F, echo=FALSE, warning=FALSE}
scmp.obj <- sc_tFit(scmp.obj)
```

# Selection of Siginificant Models
```{r, eval=FALSE, message=F, echo=FALSE, warning=FALSE}
scmp.obj <- sc.sel.features(scmp.obj,
  filter = "rsq",
  Q = 0.05
)
```

# Show Models
```{r, eval=FALSE, message=F, echo=FALSE, warning=FALSE}
showSol(scmp.obj)
```

---

### Evaluation with R-prof

```{r}
load <- function() {
  suppressPackageStartupMessages(library(maSigPro))
  suppressPackageStartupMessages(library(MASS))
  suppressPackageStartupMessages(library(scran))
  suppressPackageStartupMessages(library(tidyverse))
  suppressPackageStartupMessages(library(scMaSigPro))
  suppressPackageStartupMessages(library(utils))
  suppressPackageStartupMessages(library(profmem))
}
load()

# Load object from the /data
sce.test <- readRDS("../data/sce.test.RDS")

# Create a simple design file
design.file <- as.data.frame(colData(sce.test))
design.file$Path1 <- ifelse(design.file$Group == "Path1", 1, 0)
design.file$Path2 <- ifelse(design.file$Group == "Path2", 1, 0)
design.file$Rep <- c(1:nrow(design.file))
design.file <- design.file[, c(5, 8, 6, 7), ]

# Extract the counts
gCounts <- as.matrix(sce.test@assays@data$counts)
all(colnames(gCounts) == rownames(design.file$edesign))
```

```{r}
require(microbenchmark)
time_result <- microbenchmark(
  "scMaSigPro_Pvector" = {
    scmp.obj <- sc_tFit(scmp.obj, p.vector.sig = 0.4)
  },
  "maSigPro_Pvector" = {
    x <- capture.output(p.ob <- p.vector(
      data = as.matrix(gCounts), Q = 0.4,
      design = new.design.file,
      counts = T, family = negative.binomial(10)
    ))
  },
  times = 10
)

# Calculate the elapsed time
sum(time_result$time) / 1e9
autoplot(time_result)
```

```{r}
require(microbenchmark)
time_result <- microbenchmark(
  "scMaSigPro_Tfit" = {
    scmp.obj <- sc_tFit(scmp.obj)
  },
  "maSigPro_tfit" = {
    x <- capture.output(
      tob <- T.fit(data = p.ob)
    )
  },
  times = 10
)

# Calculate the elapsed time
sum(time_result$time) / 1e9
autoplot(time_result)
```

---

# MaSigPro to Monocle3
```{r}
library(tidyverse)
library(igraph)
# Load cds
cds <- readRDS("../../re_analysis_scRNA/setty_et_al/data/output/monocle3/Monocle3UMAPOB/rep1_m3_UMAP_OB.RDS")

# View
plot_cells(cds, show_trajectory_graph = T, color_cells_by = "pseudotime",
           cell_size = 2, label_roots = T, label_principal_points = T,
           trajectory_graph_segment_size = 3, trajectory_graph_color = "black")
           cell_size = 2, label_roots = T, label_principal_points = T)

```

## Extraction 
```{r}

source("extract_monocle3.R")
x <- extract_monocle3_components(cds = cds)

plot_cells(x$cds, show_trajectory_graph = T, color_cells_by = "Path",
           cell_size = 2, label_roots = T, label_principal_points = T) + theme(legend.position = "bottom")
plot_cells(x, show_trajectory_graph = T, color_cells_by = "Pseudotime",
           cell_size = 2, label_roots = T, label_principal_points = T)

# Identification of root cells
cell.meta.new <- as.data.frame(colData(x$cds))
unique(cell.meta.new$Path)


library(slingshot)

sce <- SingleCellExperiment(assays = List(counts = assay(cds, "counts")))
colData(sce) <- colData(x$cds)
rowData(sce) <- rowData(x$cds)
reducedDims(sce) <- reducedDims(x$cds)
sce <- slingshot(sce, clusterLabels = 'Path', reducedDim = 'UMAP', 
                 start.clus = "root", 
                 #end.clus = x$endpoints
                 )

sling.curves <- slingCurves(sce, as.df = T)
sling.time <-  slingPseudotime(sce)

# Extact Sling Data
sling.rd <- reducedDims(sce)[["UMAP"]] %>% 
            as.data.frame() %>%
            rename_with(~ c("DIM_1", "DIM_2"))

# Extract Lineage Info
ggplot(data = sling.rd, aes(x = DIM_1, y = DIM_2)) +
    geom_point(color  = "yellow")+ theme_classic()+
geom_path(inherit.aes = F, data = sling.curves %>% arrange(Order), aes(x = Dim.1, y = Dim.2,
                                                                       group = Lineage)) 
```
