# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R-CMD-Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
          - {os: macos-latest, r: 'release', r-version: '4.1.1'}
          - {os: windows-latest, r: 'release', r-version: '4.1.1'}
          - {os: ubuntu-latest, r: 'devel', r-version: '3.6.3', http-user-agent: 'release'}
          - {os: ubuntu-latest, r: 'release', r-version: '4.1.1'}

    steps:
      - uses: actions/checkout@v3
      - name: Set up R ${{ matrix.config.r-version }}
        uses: r-lib/actions/setup-r@v2  # Updated to use a stable version tag
        with:
          r-version: ${{ matrix.config.r-version }}
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
